config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  resources :categories, except: [:new, :edit, :update]
  resources :posts, except: [:index, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :title, presence: true,
                    uniqueness: true,
                    length: { maximum: 255 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  accepts_nested_attributes_for :category

  validates :text, presence: true

  before_save :set_title

  def set_title
    self.title = "Title - #{Post.count + 1}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :destroy]

  def index
    @categories = Category.all
  end

  def show
    @post = @category.posts.order(created_at: :desc)
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :destroy]

  def show; end

  def new
    @post = Post.new
    @post.build_category
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render 'new'
    end
  end

  def destroy
    @post.destroy
    redirect_to categories_path, notice: 'Post was successfully destroyed.'
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:text,
                                 :category_id,
                                 category_attributes: [:title])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>

<tbody>
  <% @categories.each do |category| %>
    <ul>
      <li><%= link_to category.title, category_path(category) %>
        <%= link_to 'delete category', category_path(category.id), method: :delete, class: 'float-right text-danger' %>
      </li>
    </ul>
  <% end %>
</tbody>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col px-0">
      <h1><%= @category.title %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col px-0">
      <% @post.each do |post| %>
        <ul>
          <li><%= link_to post.title, post %></li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YaseminBlog</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar-dark bg-dark sticky-top">
      <div class="container">
        <div class="row">
          <div class="col-3">
            <p class="h1"><%= link_to "Yasemin Blogger", root_path %></p>
          </div>
          <div class="col">
            <%= link_to 'Create new post', new_post_path, class: 'btn btn-primary mt-2 float-right' %>
          </div>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="container">
    <div class="row">
        <% if @post.errors.any? %>
          <div id="error_explanation">
            <p class="text-danger"><%= pluralize(@post.errors.count, "error") %> prohibited this category from being saved:</p>

            <ul class="text-danger">
              <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
    </div>

    <div class="row">
      <div class="col px-0">
        <%= f.label :text, 'Enter text:'%>
      </div>
      <div class="col-12 px-0">
        <%= f.text_area :text, size: "39x9"%>
      </div>
    </div>

    <div class="row">
      <div class="col px-0">
        <p>Enter category:</p>
      </div>
    </div>

    <div class="row">
      <div class="col px-0">
        <%= check_box "enable", id:"enable", type:"checkbox" %>


        <%= f.fields_for :category do |a| %>
          <%= a.label :title, 'Create new' %>
          <%= a.text_field :title, disabled: true%>
        <% end %>
      </div>
    </div>

    <p class="h6">or</p>

    <div class="row">
      <div class="col px-0">
        <%= f.label :category_id, 'Select from existing' %>
        <%= f.select :category_id, Category.all.map {|c| [c.title, c.id]} %>
      </div>
    </div>

    <div class="row">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.text %></p>

<%= link_to 'delete', post_path(@post.id), method: :delete %>